{
  "formatVersion": "1.1",
  "component": {
    "group": "com.guardsquare",
    "module": "dexguard-gradle-plugin",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "dexguard-gradle-plugin-1.2.0.jar",
          "url": "dexguard-gradle-plugin-1.2.0.jar",
          "size": 264060,
          "sha512": "3aad6552b374ff6e18b29439b4648bb271be35fc6bd4e2e05d7029bd7c770ab48238a69e6be14072ccf7414ffbb913ed1bae4663b57a7b646d5007b80118bfb9",
          "sha256": "8a288ce85500d61d4f79848dd2594cc0120b8e00823cb072628f67439d26239b",
          "sha1": "2e0cc1052b2b21c5a947b0a66c414326f190e442",
          "md5": "23d42ef8bb5ee924b740b2a64c83fdaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "dexguard-gradle-plugin-1.2.0.jar",
          "url": "dexguard-gradle-plugin-1.2.0.jar",
          "size": 264060,
          "sha512": "3aad6552b374ff6e18b29439b4648bb271be35fc6bd4e2e05d7029bd7c770ab48238a69e6be14072ccf7414ffbb913ed1bae4663b57a7b646d5007b80118bfb9",
          "sha256": "8a288ce85500d61d4f79848dd2594cc0120b8e00823cb072628f67439d26239b",
          "sha1": "2e0cc1052b2b21c5a947b0a66c414326f190e442",
          "md5": "23d42ef8bb5ee924b740b2a64c83fdaa"
        }
      ]
    }
  ]
}
